trigger: none
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/dev
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: MSI1
  steps:
  - checkout: self
    clean: true
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    condition: succeededOrFailed()
    inputs:
      SourceFolder: $(system.defaultworkingdirectory)
      Contents: |  
       '**\ARMTemplate\**'
       '**\Scripts\**'
       '**\DemoAPI\**'
      TargetFolder: $(build.artifactstagingdirectory)

# - task: AzurePowerShell@5
#   displayName: 'Azure PowerShell script: FilePath'
#   inputs:
#     azureSubscription: 'AAPDF-dev (16cc08e2-d55f-4f88-b496-822b15fa0cda)'
#     ScriptPath: Scripts/APIMDeploy.ps1
#     azurePowerShellVersion: LatestVersion
#     pwsh: true    
  # - task: AzureResourceManagerTemplateDeployment@3
  #   displayName: 'ARM Template deployment: Resource Group scope'
  #   inputs:
  #     ConnectedServiceName: "AAPDF-dev (16cc08e2-d55f-4f88-b496-822b15fa0cda)"
  #     subscriptionName: "AAPDF-dev (16cc08e2-d55f-4f88-b496-822b15fa0cda)"
  #     resourceGroupName: "demo-rg-633aee81-19b5-4ece-9369-65c85bca2c0f"
  #     # apiManagementServiceName: ${{ parameters.apiManagementServiceName }}      
  #     location: "West US 2"
  #     csmFile: ARMTemplate/AzureDeploy2.json
  #     csmParametersFile: ARMTemplate/ParameterFile2.json
  #     overrideParameters: -publisherEmail "myDemo2021-13-04-16041314@example.com" -publisherName "mr demo 2021-13-04-16043953" -sku "Developer" -skuCount "1" -location "westus2"
  #     deploymentMode: Validation
